add hero
CPI-devIT/scientific-journal pull request #13
Opened 2024-11-07 16:58 UTC by AlexOneWRLD

<img width="662" alt="image" src="https://github.com/user-attachments/assets/56c01aa6-d145-4563-b690-ea33e9218ab5">

2024-11-08 09:40 UTC, Anna-Anka requested changes
Доработки 08.11

2024-11-08 09:40 UTC, Anna-Anka commented on src/html/pages/home/_hero.html
> +    <picture class="hero__images">
Я вот думаю, это контентное изображение? Оно же имеет отношение к самому выпуску, правильно?

2024-11-08 09:40 UTC, Anna-Anka commented on src/styles/pages/home/_hero.scss
> +  background: linear-gradient(314deg,rgba(245, 235, 223, 0.4) 0%,#e3eff2 100%);
Не background, a background-image

2024-11-08 09:40 UTC, Anna-Anka commented on src/styles/pages/home/_hero.scss
> +    background: linear-gradient(295deg, rgba(245, 235, 223, 0.4) 0%, #e3eff2 100%);
Оставь градиент как на десктопе. Здесь разница в 19 градусах, никто ничего не заметит

2024-11-08 09:40 UTC, Anna-Anka commented on src/styles/pages/home/_hero.scss
> +  &__img {
А object-fit

2024-11-08 09:40 UTC, Anna-Anka commented on src/styles/pages/home/_hero.scss
> +    position: relative;
Зачем img relative

2024-11-08 09:40 UTC, Anna-Anka commented on src/html/pages/home/_hero.html
> +      <source srcset="img/home-page/hero.avif" type="image/avif" />
/ на конце одиночных тегов не ставим

2024-11-08 12:06 UTC, AlexOneWRLD commented on src/html/pages/home/_hero.html
> +    <picture class="hero__images">
Ага, плюс этот блок может же быть динамичным из-за того что выпуски меняются

2024-11-08 12:07 UTC, AlexOneWRLD commented on src/styles/pages/home/_hero.scss
> +    background: linear-gradient(295deg, rgba(245, 235, 223, 0.4) 0%, #e3eff2 100%);
done

2024-11-08 12:08 UTC, AlexOneWRLD commented on src/html/pages/home/_hero.html
> +      <source srcset="img/home-page/hero.avif" type="image/avif" />
done

2024-11-08 12:08 UTC, AlexOneWRLD commented on src/styles/pages/home/_hero.scss
> +    position: relative;
done

2024-11-08 15:13 UTC, Anna-Anka requested changes
Доработки (2) 08.11

2024-11-08 15:13 UTC, Anna-Anka commented on src/html/pages/home/_hero.html
> +    <picture class="hero__images">
Ну так, не контентное изображение тоже может быть динамичным)) Но я согласно, оно контентное, да)

2024-11-08 15:13 UTC, Anna-Anka commented on src/html/pages/home/_hero.html
> +      <img class="hero__img" src="img/home-page/hero.jpg" alt="Картинка выпуска 1.2025" width="258" height="356" loading="lazy" >
Слово "Картинка" можешь убрать)) Скринридер и так скажет, что это картинка))

2024-11-08 15:13 UTC, Anna-Anka commented on src/html/pages/home/_hero.html
> +      <h1 class="hero__title large">Выпуск 1.2025</h1>
Смотри тут какой момент. "Выпуск 1.2025" — это заголовок всей страницы? Вся страница будет посвящена этому выпуску?) Тут надо h1 выносить до секции с sr-only, а в секции уже h2

2024-11-10 11:41 UTC, AlexOneWRLD commented on src/html/pages/home/_hero.html
> +      <img class="hero__img" src="img/home-page/hero.jpg" alt="Картинка выпуска 1.2025" width="258" height="356" loading="lazy" >
done

2024-11-10 11:42 UTC, AlexOneWRLD commented on src/html/pages/home/_hero.html
> +      <h1 class="hero__title large">Выпуск 1.2025</h1>
done

2024-11-10 14:58 UTC, merged