add news block
CPI-devIT/scientific-journal pull request #17
Opened 2024-11-08 13:17 UTC by AlexOneWRLD

<img width="671" alt="image" src="https://github.com/user-attachments/assets/e4ae0dce-3367-44eb-aa4c-2c58aea810a6">

2024-11-08 15:17 UTC, Anna-Anka requested changes
Доработки 08.11

2024-11-08 15:17 UTC, Anna-Anka commented on src/html/pages/home/_news.html
> +        <button class="swiper-controls__button"></button>
Атрибут type

2024-11-08 15:17 UTC, Anna-Anka commented on src/html/pages/home/_news.html
> +<div class="news">
А js не делал?)

2024-11-10 09:56 UTC, AlexOneWRLD commented on src/html/pages/home/_news.html
> +        <button class="swiper-controls__button"></button>
done

2024-11-10 10:32 UTC, AlexOneWRLD commented on src/html/pages/home/_news.html
> +<div class="news">
done

2024-11-10 14:47 UTC, Anna-Anka requested changes
Доработки 10.11

2024-11-10 14:47 UTC, Anna-Anka commented on src/html/pages/home/_news.html
> +    <div class="news__wrapper">
Я бы сделала класс news__header, так более понятнее будет

2024-11-10 14:47 UTC, Anna-Anka commented on src/js/project/sliders/_home-slider.js
> +      nextEl: document.querySelector(".swiper-controls__button--next"),
У тебя на странице может быть больше одного элемента с таким классом. Свайпер тогда сломается. Поэтому тебе нужно искать именну ту кнопку, которая в этой секции

2024-11-10 14:47 UTC, Anna-Anka commented on src/js/project/sliders/_home-slider.js
> +      prevEl: document.querySelector(".swiper-controls__button"),
Давай добавим на prev кнопку модификатор .swiper-controls__button--prev, плиз

2024-11-10 14:47 UTC, Anna-Anka commented on src/js/project/sliders/_home-slider.js
> +    loop: true,
Вроде Макс писал, что этот слайдер не должен быть бесконечным

2024-11-10 14:47 UTC, Anna-Anka commented on src/html/pages/home/_news.html
> +<div class="news">
Может быть сделаем класс news-block, чтобы уж наверняка конкретизировать?

2024-11-10 14:47 UTC, Anna-Anka commented on src/styles/pages/home/_news.scss
> +&__wrapper{
Проверь, плиз, чтобы у заголовка во враппере не было margina

2024-11-11 12:46 UTC, AlexOneWRLD commented on src/html/pages/home/_news.html
> +    <div class="news__wrapper">
done

2024-11-11 12:49 UTC, AlexOneWRLD commented on src/js/project/sliders/_home-slider.js
> +      nextEl: document.querySelector(".swiper-controls__button--next"),
Сделал вложенность и родитель news__header

2024-11-11 12:50 UTC, AlexOneWRLD commented on src/js/project/sliders/_home-slider.js
> +    loop: true,
Не, есть комментарий что 5 новостей и бесконечно 

<img width="708" alt="image" src="https://github.com/user-attachments/assets/3d70bb80-7720-4643-9a3f-ecccd60773f0">

2024-11-11 12:54 UTC, AlexOneWRLD commented on src/html/pages/home/_news.html
> +<div class="news">
done

2024-11-11 12:56 UTC, AlexOneWRLD commented on src/styles/pages/home/_news.scss
> +&__wrapper{
done

2024-11-12 15:22 UTC, merged