add about block in about page
CPI-devIT/scientific-journal pull request #29
Opened 2024-11-12 09:30 UTC by AlexOneWRLD

<img width="520" alt="image" src="https://github.com/user-attachments/assets/797efd65-564d-4e09-a58e-ea92d7f7777d">

2024-11-12 15:06 UTC, Anna-Anka requested changes
Доработки 12.11

2024-11-12 15:06 UTC, Anna-Anka commented on src/html/pages/about/_about.html
> +        <h2 class="about__subtitle subtitle">Выходные данные СМИ</h2>
У тебя уже есть h2. Ты можешь h2 сделать один с sr-only, а "Общая информация" и "Выходные данные СМИ" будут h3. А "Наименование издания:", "Учредитель:" и т.д. — h4

2024-11-12 15:06 UTC, Anna-Anka commented on src/html/pages/about/_about.html
> +        <div class="about__text">
И это я бы делала списком. А еще лучше address, а внутри список

2024-11-12 15:06 UTC, Anna-Anka commented on src/styles/pages/about/_about.scss
> +  display: block;
А зачем display block?

2024-11-12 15:06 UTC, Anna-Anka commented on src/styles/pages/about/_about.scss
> +      justify-content: center;
flex-start

2024-11-12 15:06 UTC, Anna-Anka commented on src/styles/pages/about/_about.scss
> +  &__info,
Если у двух классов одинаковые стили и больше между ними нет никакой разницы, то может сделать одинаковые классы?)

2024-11-13 12:22 UTC, AlexOneWRLD commented on src/html/pages/about/_about.html
> +        <h2 class="about__subtitle subtitle">Выходные данные СМИ</h2>
done

2024-11-13 12:29 UTC, AlexOneWRLD commented on src/html/pages/about/_about.html
> +        <div class="about__text">
done

2024-11-13 12:30 UTC, AlexOneWRLD commented on src/styles/pages/about/_about.scss
> +      justify-content: center;
done

2024-11-13 12:31 UTC, AlexOneWRLD commented on src/styles/pages/about/_about.scss
> +  &__info,
done

2024-11-14 11:13 UTC, Anna-Anka reviewed
14.11

2024-11-14 11:13 UTC, Anna-Anka commented on src/html/pages/about/_about.html
> +        <ul class="about__items">
Может быть тут тоже dl список сделать? Как ты считаешь, подходит он тут семантически?

2024-11-14 11:13 UTC, Anna-Anka commented on src/styles/pages/about/_about.scss
> +    h4 {
Если обращайся по тегу, убирай лишний класс

2024-11-14 12:50 UTC, AlexOneWRLD commented on src/html/pages/about/_about.html
> +        <ul class="about__items">
Не, тут же нет определений, тут просто перечисление что и как и где. Обычного списка достаточно

2024-11-14 12:51 UTC, AlexOneWRLD commented on src/styles/pages/about/_about.scss
> +    h4 {
done

2024-11-15 17:26 UTC, merged