add authors block in page about
CPI-devIT/scientific-journal pull request #30
Opened 2024-11-12 10:39 UTC by AlexOneWRLD

<img width="543" alt="image" src="https://github.com/user-attachments/assets/cd0f3841-5698-4907-9de3-299a35430c1e">

2024-11-12 15:02 UTC, Anna-Anka requested changes
Доработки 12.11

2024-11-13 12:34 UTC, AlexOneWRLD commented on src/html/components/cards/_people-card.html
> +  <img class="people-card__img" src="./img/people/authors/@img." alt="Автор @author" width="120" height="120" loading="lazy">
done

2024-11-13 12:39 UTC, AlexOneWRLD commented on src/html/components/cards/_people-card.html
> +  <p>Город: @city</p>
done

2024-11-13 12:45 UTC, AlexOneWRLD commented on src/html/pages/about/_authors.html
> +<section class="authors">
Не,  стили кинул в глобал. А блок сделал один, нужно будет рил копипастить, потому что количество людей может быть разным и разные фотки и так далее

2024-11-13 12:47 UTC, AlexOneWRLD commented on src/styles/components/cards/_people-card.scss
> +  @include card(35px 40px,30px,var(--color-white));
done

2024-11-13 12:48 UTC, AlexOneWRLD commented on src/styles/components/cards/_people-card.scss
> +    border-radius: 179px;
done

2024-11-13 12:50 UTC, AlexOneWRLD commented on src/styles/pages/about/_authors.scss
> +    margin-bottom: 35px;
done

2024-11-13 12:50 UTC, AlexOneWRLD commented on src/html/components/cards/_people-card.html
> +  <p class="people-card__name caption">@name</p>
done

2024-11-14 11:08 UTC, Anna-Anka requested changes
Доработки 14.11

2024-11-14 11:08 UTC, Anna-Anka commented on src/html/components/cards/_people-card.html
> +  <dl class="people-card__items">
Список dl нужен в тех случаях, когда есть ключ и значение. У имени нет ключа, поэтому список должен начинать после. В dd берется ключ, а в dt значение. Вот пример https://htmlacademy.ru/courses/301/run/6

2024-11-14 11:08 UTC, Anna-Anka commented on src/html/pages/about/_authors.html
> +<section class="people">
Я бы people-block назвала, но смотри сам)

2024-11-14 11:08 UTC, Anna-Anka commented on src/styles/_global.scss
> +.people {
Не, это в отдельный файл

2024-11-14 12:44 UTC, AlexOneWRLD commented on src/html/components/cards/_people-card.html
> +  <dl class="people-card__items">
done

2024-11-14 12:45 UTC, AlexOneWRLD commented on src/html/pages/about/_authors.html
> +<section class="people">
done

2024-11-14 12:47 UTC, AlexOneWRLD commented on src/styles/_global.scss
> +.people {
done

2024-11-14 13:21 UTC, merged