add news-card and page all-news, refactor vars and global
CPI-devIT/scientific-journal pull request #4
Opened 2024-11-05 10:17 UTC by AlexOneWRLD

<img width="535" alt="image" src="https://github.com/user-attachments/assets/c0ce1281-2948-47c4-972c-ee6b969f1afd">

2024-11-05 13:55 UTC, Anna-Anka requested changes
Доработки 05.11

2024-11-05 13:55 UTC, Anna-Anka commented on package.json
> +		"gulp": "^5.0.0",
^ вот эти крышечки убери, плиз. Чтобы у нас были четко зафиксированы версии

2024-11-05 13:55 UTC, Anna-Anka commented on src/html/components/cards/_news-card.html
> +  <a class="news-card__list" href="@href">
Как я поняла, ссылкой является только заголовок. И почему класс list? Это же не список

2024-11-05 13:55 UTC, Anna-Anka commented on src/html/components/cards/_news-card.html
> +    <time class="news-card__date" datetime="@date">
для атрибута datetime вроде другой формат даты нужен, не как у нас в макете

2024-11-05 13:55 UTC, Anna-Anka commented on src/html/pages/all-news/_news.html
> +      <li class="news__item news__item--horizontal">
А зачем модификатор?

2024-11-05 13:55 UTC, Anna-Anka commented on src/html/pages/all-news/_news.html
> +  <h2 class="news__title title-page">Новости</h2>
Это заголовок страницы (h1)

2024-11-05 13:55 UTC, Anna-Anka commented on src/html/pages/all-news/_news.html
> +    <a class="news__button button" href="#">Показать ещё</a>
По клику мы никуда не переходим)

2024-11-05 13:55 UTC, Anna-Anka commented on src/styles/_global.scss
> +  transition: background-color 0.4s;
С 41 по 49 строки можешь пока убрать, я подобное в своей ветке писала. И думаю, что в макете в ui kit первая кнопка — это не состояние active, a disable

2024-11-05 13:55 UTC, Anna-Anka commented on src/styles/components/cards/_news-card.scss
> +&__list {
Все эти стили (кроме font-weight) нужно на саму карточку писать

2024-11-05 14:12 UTC, AlexOneWRLD commented on package.json
> +		"gulp": "^5.0.0",
done

2024-11-05 14:13 UTC, AlexOneWRLD commented on src/html/components/cards/_news-card.html
> +  <a class="news-card__list" href="@href">
Я уточнил и ты права))

2024-11-05 14:16 UTC, AlexOneWRLD commented on src/html/components/cards/_news-card.html
> +  <a class="news-card__list" href="@href">
done

2024-11-05 14:25 UTC, AlexOneWRLD commented on src/html/components/cards/_news-card.html
> +    <time class="news-card__date" datetime="@date">
done

2024-11-05 14:33 UTC, AlexOneWRLD commented on src/html/pages/all-news/_news.html
> +    <a class="news__button button" href="#">Показать ещё</a>
done

2024-11-05 14:35 UTC, AlexOneWRLD commented on src/styles/_global.scss
> +padding: 33px 0;
done

2024-11-05 17:35 UTC, AlexOneWRLD commented on src/html/components/cards/_news-card.html
> +    <a class="news-card__title" href="@href">@title</a>
done

2024-11-05 17:36 UTC, AlexOneWRLD commented on src/html/components/cards/_news-card.html
> +      @date-day.@date-month.@date-year
Но если Рома скажет что сложно, сделаю все одной переменной

2024-11-05 17:37 UTC, AlexOneWRLD commented on src/html/pages/all-news/_news.html
> +  <div class="news__list container">
Доп падинги

2024-11-05 17:40 UTC, AlexOneWRLD commented on src/styles/pages/all-news/_news.scss
> +    padding: 100px 65px;
done

2024-11-05 17:45 UTC, AlexOneWRLD commented on src/html/pages/all-news/_news.html
> +  <h1 class="news__title title-page">Новости</h1>
done

2024-11-06 16:04 UTC, Anna-Anka requested changes
Доработки 06.11

2024-11-06 16:04 UTC, Anna-Anka commented on src/html/components/cards/_news-card.html
> +  <time class="news-card__date" datetime="@date-year-@date-month-@date-day">
Глянь, как в конференции делали. У нас была одна переменна (например date) для текста и одна (например datetime) для атрибута. Может так же сделаем?

2024-11-06 16:04 UTC, Anna-Anka commented on src/html/pages/all-news/_news.html
> +    <button class="news__button button" href="#">Показать ещё</butto>
href у button?)

2024-11-06 16:04 UTC, Anna-Anka commented on src/styles/pages/all-news/_news.scss
> +  padding: 100px 45px;
А зачем тут паддинги по бокам? За это же контейнер отвечает

2024-11-07 12:07 UTC, AlexOneWRLD commented on src/html/pages/all-news/_news.html
> +    <button class="news__button button" href="#">Показать ещё</butto>
done)

2024-11-07 12:08 UTC, AlexOneWRLD commented on src/styles/pages/all-news/_news.scss
> +  padding: 100px 45px;
done

2024-11-07 12:12 UTC, AlexOneWRLD commented on src/html/components/cards/_news-card.html
> +  <time class="news-card__date" datetime="@date-year-@date-month-@date-day">
done

2024-11-07 15:37 UTC, Anna-Anka reviewed
Доработки 07.11

2024-11-07 15:37 UTC, Anna-Anka commented on src/html/pages/all-news/_news.html
> +    <button class="news__button button">Показать ещё</butto>
Атрибут type. И в закрывающемся теге допиши "n")

2024-11-07 15:37 UTC, Anna-Anka commented on src/styles/components/cards/_news-card.scss
> +.news-card {
Используй миксин card и убери лишний код

2024-11-08 10:44 UTC, AlexOneWRLD commented on src/html/pages/all-news/_news.html
> +    <button class="news__button button">Показать ещё</butto>
done

2024-11-08 11:39 UTC, AlexOneWRLD commented on src/styles/components/cards/_news-card.scss
> +  font-weight: 300;
done

2024-11-08 11:43 UTC, AlexOneWRLD commented on src/styles/components/cards/_news-card.scss
> +.news-card {
done

2024-11-08 11:44 UTC, AlexOneWRLD commented on src/styles/components/cards/_news-card.scss
> +  &__title {
done

2024-11-08 14:48 UTC, Anna-Anka reviewed
Доработки 08.11

2024-11-08 14:48 UTC, Anna-Anka commented on src/styles/components/cards/_news-card.scss
> +  &__link {
Миксин link

2024-11-08 14:48 UTC, Anna-Anka commented on src/styles/pages/all-news/_news.scss
> +    margin-bottom: 30px;
сделай margin-bottom через not last-child, плиз. А то может быть такое, что кнопки не будет

2024-11-08 15:25 UTC, AlexOneWRLD commented on src/styles/pages/all-news/_news.scss
> +    margin-bottom: 30px;
done

2024-11-08 16:38 UTC, merged