add header non burger menu
CPI-devIT/scientific-journal pull request #8
Opened 2024-11-06 15:14 UTC by AlexOneWRLD

<img width="764" alt="image" src="https://github.com/user-attachments/assets/ecdc6130-b4ff-4ce5-98c0-9e3270de60f8">

2024-11-06 17:29 UTC, Anna-Anka requested changes
Доработки 06.11

2024-11-06 17:29 UTC, Anna-Anka commented on src/styles/components/blocks/header/_header.scss
> +    max-width: 1295px;
За это отвечает контейнер

2024-11-06 17:29 UTC, Anna-Anka commented on src/styles/components/blocks/header/_header.scss
> +  &__logo {
На глобальные стили задавала

2024-11-07 12:13 UTC, AlexOneWRLD commented on src/html/components/blocks/_header.html
> +          <a class="header__link" href="#" target="_blank"> О журнале </a>
done

2024-11-07 12:14 UTC, AlexOneWRLD commented on src/html/components/blocks/_header.html
> +        <span class="header__person"></span>
А иконка не будет меняться при заходе юзера?

2024-11-07 12:15 UTC, AlexOneWRLD commented on src/styles/_global.scss
> +	padding: 0 30px;
Я по макету сделал 30) 
Ну сделаю 20))

2024-11-07 12:17 UTC, AlexOneWRLD commented on src/styles/components/blocks/header/_header.scss
> +    max-width: 1295px;
done

2024-11-07 12:17 UTC, AlexOneWRLD commented on src/styles/components/blocks/header/_header.scss
> +  &__logo {
done

2024-11-07 12:23 UTC, AlexOneWRLD commented on src/html/components/blocks/_header.html
> +        <span class="header__person"></span>
done

2024-11-07 15:41 UTC, Anna-Anka requested changes
Доработки 07.11

2024-11-07 15:41 UTC, Anna-Anka commented on src/html/components/blocks/_header.html
> +      <ul class="header__menu">
У тебя ul и li с одинаковым классом

2024-11-07 15:41 UTC, Anna-Anka commented on src/html/components/blocks/_header.html
> +          class="logo__img"
Не переноси атрибуты

2024-11-07 15:41 UTC, Anna-Anka commented on src/html/components/blocks/_header.html
> +        <a class="header__registration" href="#registration-block">Войти</a>
1) #registration-block у нас нет в этом макете
2) По клику будут открываться модалки, мы никуда не переходим)

2024-11-07 15:41 UTC, Anna-Anka commented on src/html/components/blocks/_header.html
> +      <button
Атрибуты не переноси

2024-11-07 15:41 UTC, Anna-Anka commented on src/styles/components/blocks/header/_header.scss
> +  position: absolute;
Ты хочешь сразу absolute делать?

2024-11-07 15:41 UTC, Anna-Anka commented on src/styles/components/blocks/header/_header.scss
> +  &__link,
Если у них одинаковые стили, то может задать один класс на двоих? И для эффектов можешь использовать класс link

2024-11-07 15:41 UTC, Anna-Anka commented on src/styles/components/blocks/header/_header.scss
> +    &::after {
Подумай, может тут использовать icon или circle миксин

2024-11-08 11:49 UTC, AlexOneWRLD commented on src/html/components/blocks/_header.html
> +      <ul class="header__menu">
done

2024-11-08 11:49 UTC, AlexOneWRLD commented on src/html/components/blocks/_header.html
> +          class="logo__img"
done

2024-11-08 11:52 UTC, AlexOneWRLD commented on src/html/components/blocks/_header.html
> +      <button
done

2024-11-08 11:55 UTC, AlexOneWRLD commented on src/styles/components/blocks/header/_header.scss
> +  position: absolute;
Просто затупил думал что он липкий

2024-11-08 11:55 UTC, AlexOneWRLD commented on src/styles/components/blocks/header/_header.scss
> +  position: absolute;
done

2024-11-08 11:56 UTC, AlexOneWRLD commented on src/styles/components/blocks/header/_header.scss
> +  &__link,
done

2024-11-08 12:02 UTC, AlexOneWRLD commented on src/styles/components/blocks/header/_header.scss
> +    &::after {
done

2024-11-08 14:50 UTC, Anna-Anka commented on src/html/components/blocks/_header.html
> +        <img class="logo__img" src="img/logos/sj.svg" alt="Логотип научного журнала" width="191" height="42" />
Опять / в конце)

2024-11-08 14:50 UTC, Anna-Anka commented on src/styles/components/blocks/header/_header.scss
> +  z-index: 20;
z-index без position не имеет смысла

2024-11-08 14:51 UTC, Anna-Anka commented on src/styles/components/blocks/header/_header.scss
> +    transition: color 0.4s;
Миксин link

2024-11-10 10:48 UTC, AlexOneWRLD commented on src/html/components/blocks/_header.html
> +    <div class="container header__container">
done

2024-11-10 10:48 UTC, AlexOneWRLD commented on src/html/components/blocks/_header.html
> +        <img class="logo__img" src="img/logos/sj.svg" alt="Логотип научного журнала" width="191" height="42" />
done

2024-11-10 10:49 UTC, AlexOneWRLD commented on src/styles/components/blocks/header/_header.scss
> +  z-index: 20;
done

2024-11-10 10:50 UTC, AlexOneWRLD commented on src/styles/components/blocks/header/_header.scss
> +    transition: color 0.4s;
done

2024-11-10 14:59 UTC, merged